#ifndef ESTRUCTURA_DE_DATOS_I_2020_TPFINAL_MATEMATICA_H
#define ESTRUCTURA_DE_DATOS_I_2020_TPFINAL_MATEMATICA_H

int max(int a, int b);

int min(int a, int b);

#endif //ESTRUCTURA_DE_DATOS_I_2020_TPFINAL_MATEMATICA_H
